//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JunSuCpp.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_JunSuCppTYPE                130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_WORKSPACE               133
#define ID_VIEW_MAPLAYERS               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_WORKSPACE_VIEW              155
#define IDS_MAPLAYERS_VIEW              156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_WORKSPACE_VIEW              161
#define IDI_WORKSPACE_VIEW_HC           162
#define IDI_MAPLAYERS_VIEW              163
#define IDI_MAPLAYERS_VIEW_HC           164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_WORKSPACE_VIEW              175
#define IDB_WORKSPACE_VIEW_24           176
#define IDB_MAPLAYERS_VIEW              177
#define IDB_MAPLAYERS_VIEW_24           178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_LIST_POPUP_DATASET          313
#define IDR_LIST_POPUP_MAP              315
#define IDR_LIST_POPUP_LAYER            317
#define IDR_LIST_POPUP_SCENCE           318
#define IDR_LIST_POPUP_DATASOURCE       319
#define IDR_POPUP_MAPVIEW               320
#define IDD_DIALOG_OpenWK_DB            321
#define IDC_EDIT_DB_Host                1001
#define IDC_EDIT_DB_Port                1002
#define IDC_EDIT_DB_Name                1003
#define IDC_EDIT_UserPassword           1004
#define IDC_EDIT5                       1005
#define IDC_EDIT_DB_WKName              1005
#define IDC_EDIT_UserName               1006
#define IDC_COMBO_DB_Type               1008
#define IDC_Text_WK_DS_Name             1009
#define ID_DATASOURCE_OPENLOCAL         32771
#define ID_DATASOURCE_OPENWEB           32772
#define ID_DATASOURCE_OPENFROMDATABASE  32773
#define ID_WORKSPACE_OPENFROMLOCAL      32774
#define ID_WORKSPACE_OPENFROMDATABASE   32775
#define ID_DATA_BUILDNETWORK            32776
#define ID_ANALYST_NETWORKANALYST       32777
#define ID_EDIT_DRAWPOINT               32778
#define ID_EDIT_DRAWLINE                32779
#define ID_EDIT_DRAWREGION              32780
#define ID_EDIT_EDITLINE                32781
#define ID_EDIT_EDITNODES               32782
#define ID_MEASURE_LENGTH               32783
#define ID_MEASURE_AREA                 32784
#define ID_DATASOURCE_OPENFROMLOCAL     32785
#define ID_LAYER_EDITABLE               32786
#define ID_LAYER_SELECTABLE             32787
#define ID_LAYER_VISIBLE                32788
#define ID_LAYER_REMOVE                 32789
#define ID_MAP_OPEN                     32790
#define ID_DATASET_ADDTOMAP             32791
#define ID_SCENCE_OPEN                  32792
#define ID_DATASOURCE_ADDDATA           32793
#define ID_DATASOURCE_IMPORTDATASET     32794
#define ID_DATASOURCE_EXPORTDATASET     32795
#define ID_DATASOURCE_CLOSE             32796
#define ID_MAP_DELETE                   32797
#define ID_SCENCE_DELETE                32798
#define ID_DATASET_ADDTONEWMAP          32799
#define ID_DATASET_DELETE               32800
#define ID_MAP_SAVE                     32801
#define ID_EDIT_SELECT                  32802
#define ID_EDIT_PAN                     32803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        325
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
